name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MAIN_DEPLOY_KEY }}
          script: |
            const { owner } = context.repo;
            await github.rest.actions.createWorkflowDispatch({
              owner,
              repo: 'mauris.github.io',
              workflow_id: 'deploy.yml',
              ref: 'main',
            });
