name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              'mauris,
              'mauris.github.io',
              'workflows/deploy.yml',
              'main',
            });
